telegram:
  admin_ids:
    - 424826379
  chat_ids:
    - "@dsomni_test_channel"
    - -4883974576
webapp:
  url: https://f6e2268f5aa0.ngrok-free.app/
parts:
  holibot:
    enabled: true
    type: HoliBot
    scheduler:
      post_time_utc: "22:52"
      post_start_time_utc: "22:53"
      post_end_time_utc: "22:54"
    scraper:
      holiday_url: https://www.checkiday.com/
      holiday_limit: 2
    llm:
      concurrency_limit: 5
      text_model: qwen-3-32b
      image_model: flux
      text_prompt:
        "Generate a short, funny, and engaging caption for the holiday:
        '{holiday_name}'."
      image_prompt: "A humorous, creative image for the holiday: '{holiday_name}'."
    telegram_settings:
      caption_character_limit: 1024
      post_delay_seconds: 1
  jokebot:
    enabled: true
    type: JokeGenerator
    llm:
      text_model: qwen-3-30b
      joke_prompt: Tell me a short hilarious joke
      joke_prompt_with_topic: Tell me a short, funny joke about {topic}.
    telegram_settings:
      post_delay_seconds: 1
      batch_size: 5
      batch_delay_seconds: 2
